import { useState } from "react";
import { MapPinned, Pencil, Plus, Star, Trash2 } from "lucide-react";
import { Alert } from "@/components/ui/Alert";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { Input } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/ui/PageHeader";
import { useCreateRoute, useDeleteRoute, useFrequentRoutes, useRouteHistory, useSelectRouteToday, useUpdateRoute } from "@/features/platform/hooks";
import type { RouteInput, RouteItem } from "@/features/platform/types";
import { formatPlatformDate, MapLink, platformError } from "@/features/platform/pages/shared";

const EMPTY: RouteInput = { nombre: "", origen: "", origenLat: 0, origenLng: 0, destino: "", destinoLat: 0, destinoLng: 0, distanciaKm: 0, duracionEstimadaMin: 0, esFrecuente: true };
function numeric(value: string): number { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }

export function RoutesPage() {
  const frequent = useFrequentRoutes(); const history = useRouteHistory(); const create = useCreateRoute(); const update = useUpdateRoute(); const remove = useDeleteRoute(); const select = useSelectRouteToday();
  const [editing, setEditing] = useState<RouteItem | null>(null); const [formOpen, setFormOpen] = useState(false); const [deleting, setDeleting] = useState<RouteItem | null>(null); const [form, setForm] = useState<RouteInput>(EMPTY); const [notice, setNotice] = useState<string | null>(null);
  const openCreate = () => { setEditing(null); setForm(EMPTY); setFormOpen(true); };
  const openEdit = (item: RouteItem) => { setEditing(item); setForm({ nombre: item.nombre, origen: item.origen, origenLat: item.origenLat, origenLng: item.origenLng, destino: item.destino, destinoLat: item.destinoLat, destinoLng: item.destinoLng, distanciaKm: item.distanciaKm, duracionEstimadaMin: item.duracionEstimadaMin, esFrecuente: item.esFrecuente }); setFormOpen(true); };
  const closeForm = () => { setFormOpen(false); setEditing(null); setForm(EMPTY); };
  const submit = () => { if (!form.nombre.trim() || !form.origen.trim() || !form.destino.trim()) return; const options = { onSuccess: () => { closeForm(); setNotice(editing ? "Ruta actualizada." : "Ruta creada."); } }; if (editing) update.mutate({ id: editing.id, input: form }, options); else create.mutate(form, options); };
  const busyError = create.error || update.error;
  return <div className="space-y-8"><PageHeader icon={MapPinned} title="Rutas" description="Administra rutas frecuentes y consulta su historial de uso." actions={<Button leftIcon={<Plus className="size-4" />} onClick={openCreate}>Nueva ruta</Button>} />{notice ? <Alert tone="success">{notice}</Alert> : null}
    <section><h2 className="mb-3 text-lg font-semibold">Rutas frecuentes</h2>{frequent.isPending ? <div className="skeleton h-56" /> : null}{frequent.isError ? <ErrorState title="No se pudieron cargar las rutas" description={platformError(frequent.error)} onRetry={() => void frequent.refetch()} /> : null}{frequent.data?.length === 0 ? <EmptyState icon={MapPinned} title="Sin rutas frecuentes" description="Registra una ruta para seleccionarla en tus próximos viajes." /> : null}{frequent.data && frequent.data.length > 0 ? <div className="grid gap-4 md:grid-cols-2">{frequent.data.map((item) => <Card key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.nombre}</p><p className="mt-1 text-sm text-secondary">{item.origen} → {item.destino}</p></div>{item.seleccionadaHoy ? <Badge tone="brand" icon={<Star className="size-3" />}>Hoy</Badge> : null}</div><p className="mt-3 text-sm text-muted">{item.distanciaKm} km · {item.duracionEstimadaMin} min</p><div className="mt-3"><MapLink lat={item.destinoLat} lng={item.destinoLng} label="Ver destino" /></div><div className="mt-4 flex flex-wrap gap-2">{!item.seleccionadaHoy ? <Button size="sm" variant="outline" loading={select.isPending} onClick={() => select.mutate(item.id, { onSuccess: () => setNotice("Ruta seleccionada para hoy.") })}>Seleccionar hoy</Button> : null}<Button size="sm" variant="ghost" leftIcon={<Pencil className="size-4" />} onClick={() => openEdit(item)}>Editar</Button><Button size="sm" variant="ghost" leftIcon={<Trash2 className="size-4" />} onClick={() => setDeleting(item)}>Eliminar</Button></div></Card>)}</div> : null}</section>
    <section><h2 className="mb-3 text-lg font-semibold">Historial</h2>{history.isPending ? <div className="skeleton h-40" /> : null}{history.isError ? <ErrorState title="No se pudo cargar el historial" description={platformError(history.error)} onRetry={() => void history.refetch()} /> : null}{history.data && history.data.length > 0 ? <div className="space-y-2">{history.data.map((item) => <Card key={`${item.id}-${item.usadaEn}`} padding="sm"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{item.nombre}</span><span className="text-xs text-muted">{formatPlatformDate(item.usadaEn)}</span></div></Card>)}</div> : <p className="text-sm text-muted">Sin uso registrado.</p>}</section>
    <Modal open={formOpen} onClose={closeForm} title={editing ? "Editar ruta" : "Nueva ruta"} className="max-w-2xl"><div className="grid gap-4 sm:grid-cols-2"><Input placeholder="Nombre" value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} /><Input placeholder="Distancia km" type="number" value={form.distanciaKm} onChange={(e) => setForm({ ...form, distanciaKm: numeric(e.target.value) })} /><Input placeholder="Origen" value={form.origen} onChange={(e) => setForm({ ...form, origen: e.target.value })} /><Input placeholder="Destino" value={form.destino} onChange={(e) => setForm({ ...form, destino: e.target.value })} /><Input placeholder="Latitud origen" type="number" value={form.origenLat} onChange={(e) => setForm({ ...form, origenLat: numeric(e.target.value) })} /><Input placeholder="Longitud origen" type="number" value={form.origenLng} onChange={(e) => setForm({ ...form, origenLng: numeric(e.target.value) })} /><Input placeholder="Latitud destino" type="number" value={form.destinoLat} onChange={(e) => setForm({ ...form, destinoLat: numeric(e.target.value) })} /><Input placeholder="Longitud destino" type="number" value={form.destinoLng} onChange={(e) => setForm({ ...form, destinoLng: numeric(e.target.value) })} /><Input placeholder="Duración estimada min" type="number" value={form.duracionEstimadaMin} onChange={(e) => setForm({ ...form, duracionEstimadaMin: numeric(e.target.value) })} /></div>{busyError ? <Alert className="mt-4" tone="error">{platformError(busyError)}</Alert> : null}<div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={closeForm}>Cancelar</Button><Button loading={create.isPending || update.isPending} onClick={submit}>Guardar</Button></div></Modal>
    <ConfirmDialog open={Boolean(deleting)} title="Eliminar ruta" description={deleting?.nombre ?? ""} confirmLabel="Eliminar" danger loading={remove.isPending} error={remove.isError ? platformError(remove.error) : null} onCancel={() => setDeleting(null)} onConfirm={() => deleting && remove.mutate(deleting.id, { onSuccess: () => { setDeleting(null); setNotice("Ruta eliminada."); } })} />
  </div>;
}
